#设置微服务端口
server:
  port: 30000

  #配置微服务名称
  application:
    name: mall-third-party
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  level:
    com.zyl.mall: debug

alibaba:
  cloud:
    access-key:
    secret-key:
    oss:
      endpoint: oss-cn-chengdu.aliyuncs.com
      bucket: mall-zyl-zj
